### ISSUE TITLE
HOW TO USE CA?

### ISSUE THREAD

**Issue by cornmagic** [teamclairvoyant/hadoop-deployment-bash#53]
How to sign csr using openssl?
Is there any document about how to use ca?

**Comment by razorsedge** [comment]
There are [lots of resources](https://www.google.com/search?q=openssl+certificate+authority) that can guide you on using `openssl` to create a certificate authority and sign CSRs.  I like Jamie Nguyen's [OpenSSL Certificate Authority](https://jamielinux.com/docs/openssl-certificate-authority/).
